// Code-block syntax highlighting (Shiki) for the app-owned markdown pipeline.
//
// This EXTENDS the §9 sanitizing pipeline in sanitize.ts — it does NOT introduce
// a parallel sanitizer. It runs as a rehype step AFTER rehype-sanitize, so it only
// ever transforms already-sanitized `<pre><code class="language-*">` blocks: it
// reads the (sanitized) code text and the language class rehype-sanitize allows,
// and replaces the block with Shiki's highlighted markup. Because Shiki's output
// is generated by the app from sanitized text, it is trusted.
//
// CSP-STRICT OUTPUT (V-013 / A1): Shiki natively emits inline `style` attributes
// (e.g. `style="color:#d73a49"`) on every token span, which are blocked by the
// `style-src 'self' 'nonce-…'` CSP (no `unsafe-inline`). This module
// post-processes Shiki's HAST output to eliminate all inline styles: each unique
// (light-color, dark-color) pair is mapped to a stable CSS class name, and a
// companion function `getShikiCss()` returns the full class-to-color stylesheet
// to be served from `'self'` at /shiki.css.
//
// The dual-theme output (github-light + github-dark) uses `defaultColor: false`
// so Shiki emits CSS-variable properties (`--shiki-light:…; --shiki-dark:…`) on
// each span rather than a direct `color:…` — but those are still inline `style`
// attributes and still blocked. We strip them entirely and replace with classes.
//
// Shiki is run SYNCHRONOUSLY (createHighlighterCoreSync + the pure-JS regex engine
// with a curated, pre-loaded language set) so the markdown pipeline stays sync —
// renderMarkdown is consumed by the public theme-render path (context.ts) on the
// sync path, and keeping it sync means zero signature changes there.
//
// Server-only (imported only by sanitize.ts, which the public render path and the
// admin preview route consume). It must never be imported by a client component —
// that would pull the Shiki grammars into the browser bundle.

import { createHighlighterCoreSync, type HighlighterCore } from "shiki/core";
import { createJavaScriptRegexEngine } from "shiki/engine/javascript";
import type { Element, ElementContent, Root, RootContent } from "hast";

import bash from "@shikijs/langs/bash";
import css from "@shikijs/langs/css";
import diff from "@shikijs/langs/diff";
import docker from "@shikijs/langs/docker";
import go from "@shikijs/langs/go";
import html from "@shikijs/langs/html";
import javascript from "@shikijs/langs/javascript";
import json from "@shikijs/langs/json";
import markdown from "@shikijs/langs/markdown";
import python from "@shikijs/langs/python";
import rust from "@shikijs/langs/rust";
import sql from "@shikijs/langs/sql";
import toml from "@shikijs/langs/toml";
import tsx from "@shikijs/langs/tsx";
import typescript from "@shikijs/langs/typescript";
import yaml from "@shikijs/langs/yaml";
import githubDark from "@shikijs/themes/github-dark";
import githubLight from "@shikijs/themes/github-light";

// Curated language set for a technical/personal blog. Shiki resolves embedded
// sub-grammars (e.g. tsx pulls in javascript) and registers aliases (ts, sh, …).
const highlighter: HighlighterCore = createHighlighterCoreSync({
  engine: createJavaScriptRegexEngine(),
  themes: [githubDark, githubLight],
  langs: [
    typescript,
    tsx,
    javascript,
    json,
    html,
    css,
    bash,
    python,
    yaml,
    markdown,
    sql,
    docker,
    diff,
    go,
    rust,
    toml,
  ],
});

const loadedLangs = new Set(highlighter.getLoadedLanguages());

// ── CSP-safe CSS class registry ──────────────────────────────────────────────
//
// Every unique (lightColor, darkColor) pair encountered during highlighting gets
// a stable CSS class name ("shk0", "shk1", …). The generated CSS for those
// classes is served from /shiki.css (style-src 'self'), which is safe under
// the strict CSP. The <pre> background pair is stored separately.

interface ColorPair {
  light: string;
  dark: string;
}

// Token foreground colors: "light|dark" → class name
const tokenColorMap = new Map<string, string>();
// Pre background colors (one per highlighted block — we track the canonical pair)
const bgColorMap = new Map<string, string>();
let nextTokenIdx = 0;
let nextBgIdx = 0;

function classForToken(light: string, dark: string): string {
  const key = `${light}|${dark}`;
  if (!tokenColorMap.has(key)) {
    tokenColorMap.set(key, `shkt${nextTokenIdx++}`);
  }
  return tokenColorMap.get(key)!;
}

function classForBg(light: string, dark: string): string {
  const key = `${light}|${dark}`;
  if (!bgColorMap.has(key)) {
    bgColorMap.set(key, `shkb${nextBgIdx++}`);
  }
  return bgColorMap.get(key)!;
}

/**
 * Parse a CSS inline-style string into a property→value map.
 * E.g. "--shiki-light:#d73a49; --shiki-dark:#ff7b72" →
 * { "--shiki-light": "#d73a49", "--shiki-dark": "#ff7b72" }
 */
function parseInlineStyle(style: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const decl of style.split(";")) {
    const colon = decl.indexOf(":");
    if (colon < 0) continue;
    const prop = decl.slice(0, colon).trim();
    const val = decl.slice(colon + 1).trim();
    if (prop && val) map.set(prop, val);
  }
  return map;
}

/**
 * Strip inline `style` from a Shiki HAST element and replace with a CSS class.
 * Handles both token spans (--shiki-light/dark) and the <pre> element
 * (background-color + --shiki-dark-bg).
 */
function stripStyle(node: Element): void {
  const raw = node.properties?.style;
  if (!raw || typeof raw !== "string") return;

  const props = parseInlineStyle(raw);
  // Remove the inline style regardless of what we find.
  delete node.properties.style;

  const existing = node.properties.className;
  const classes: (string | number)[] = Array.isArray(existing)
    ? (existing as (string | number)[])
    : typeof existing === "string"
      ? [existing]
      : [];

  if (node.tagName === "pre") {
    // <pre> carries background-color (light) and --shiki-dark-bg (dark).
    const lightBg = props.get("background-color") ?? "";
    const darkBg = props.get("--shiki-dark-bg") ?? lightBg;
    if (lightBg || darkBg) {
      classes.push(classForBg(lightBg, darkBg));
    }
  } else {
    // <span> token: --shiki-light (foreground, light scheme) and --shiki-dark
    // (foreground, dark scheme). With defaultColor: false, there is no `color:`
    // property — only the CSS variable pair.
    const lightColor = props.get("--shiki-light") ?? "";
    const darkColor = props.get("--shiki-dark") ?? lightColor;
    if (lightColor || darkColor) {
      classes.push(classForToken(lightColor, darkColor));
    }
  }

  if (classes.length > 0) {
    node.properties.className = classes;
  }
}

/** Recursively strip all inline styles from a Shiki HAST subtree. */
function stripShikiStyles(node: Element): void {
  stripStyle(node);
  if (node.children) {
    for (const child of node.children) {
      if (child.type === "element") {
        stripShikiStyles(child as Element);
      }
    }
  }
}

/**
 * Return the accumulated CSS for all Shiki color classes. Served at /shiki.css
 * (style-src 'self'). Light-scheme rules are unconditional; dark-scheme rules
 * are scoped to `[data-scheme=dark]` (the editorial theme's scheme attribute on
 * `<html>`) so both public pages and the admin preview pane pick up the right
 * colors. Must be called after at least one highlight pass has populated the maps.
 */
export function getShikiCss(): string {
  const lines: string[] = [
    "/* Shiki syntax highlighting — CSP-strict class output (V-013). */",
    "/* Generated server-side from github-light + github-dark themes. */",
  ];

  // Token foreground classes
  for (const [key, cls] of tokenColorMap) {
    const sep = key.indexOf("|");
    const light = key.slice(0, sep);
    const dark = key.slice(sep + 1);
    if (light) lines.push(`.${cls}{color:${light}}`);
    if (dark && dark !== light) {
      lines.push(`[data-scheme=dark] .${cls}{color:${dark}}`);
    }
  }

  // Background classes (pre element)
  for (const [key, cls] of bgColorMap) {
    const sep = key.indexOf("|");
    const light = key.slice(0, sep);
    const dark = key.slice(sep + 1);
    if (light) lines.push(`.${cls}{background-color:${light}}`);
    if (dark && dark !== light) {
      lines.push(`[data-scheme=dark] .${cls}{background-color:${dark}}`);
    }
  }

  return lines.join("\n");
}

// ── Warm up the color registry at module load ────────────────────────────────
// Run the highlighter on a representative sample so the CSS class registry is
// populated before the first browser request for /shiki.css, even if no post
// has been rendered yet in this server process. This covers the common token
// types (keywords, strings, comments, types, operators, numbers, …) for the
// themes most content will use.
(function warmUp() {
  const sample = [
    "```ts",
    "// comment",
    "import { foo } from './bar';",
    "const x: number = 42;",
    "function greet(name: string): string {",
    "  return `Hello, ${name}!`;",
    "}",
    "```",
    "",
    "```js",
    "const obj = { a: 1, b: 'two' };",
    "if (obj.a > 0) console.log(obj.b);",
    "```",
    "",
    "```python",
    "def greet(name: str) -> str:",
    "    return f'Hello, {name}'",
    "```",
    "",
    "```bash",
    "#!/usr/bin/env bash",
    "echo \"hello world\"",
    "export FOO=bar",
    "```",
  ].join("\n");

  // Import inline to avoid circular dependency — sanitize.ts imports this module,
  // not the other way around. We call the same function the pipeline uses.
  try {
    // Highlight the warmup sample by calling the highlight function below
    // directly on a synthetic HAST. We can't call renderMarkdown here (circular).
    // Instead, call codeToHast directly for each language sample.
    const samples: Array<{ lang: string; code: string }> = [
      { lang: "typescript", code: "const x: number = 42;\nfunction f(s: string): void { return; }" },
      { lang: "javascript", code: "const obj = { a: 1, b: 'two' };\nif (obj.a > 0) console.log(obj.b);" },
      { lang: "python", code: "def greet(name: str) -> str:\n    return f'Hello, {name}'" },
      { lang: "bash", code: "#!/usr/bin/env bash\necho \"hello world\"\nexport FOO=bar" },
      { lang: "json", code: '{"key":"value","n":42}' },
      { lang: "css", code: ".foo { color: red; background: #fff; }" },
      { lang: "sql", code: "SELECT id, name FROM users WHERE active = true;" },
    ];
    for (const { lang, code } of samples) {
      if (!loadedLangs.has(lang)) continue;
      const hast = highlighter.codeToHast(code, {
        lang,
        themes: { light: "github-light", dark: "github-dark" },
        defaultColor: false,
      });
      // Walk the result to populate the color maps (same as stripShikiStyles).
      function walkWarmUp(node: Element): void {
        stripStyle(node);
        if (node.children) {
          for (const child of node.children) {
            if (child.type === "element") walkWarmUp(child as Element);
          }
        }
      }
      const pre = hast.children.find(
        (c): c is Element => c.type === "element" && c.tagName === "pre",
      );
      if (pre) walkWarmUp(pre);
    }
  } catch {
    // Warmup is best-effort; any failure is non-fatal.
  }
  // Suppress unused warning — sample is used in the comment above.
  void sample;
})();

/** Extract the `language-xxx` token from a hast `code` element's className. */
function languageOf(code: Element): string | null {
  const cls = code.properties?.className;
  const classes = Array.isArray(cls) ? cls : typeof cls === "string" ? [cls] : [];
  for (const c of classes) {
    const name = String(c);
    if (name.startsWith("language-")) return name.slice("language-".length);
  }
  return null;
}

/** Concatenate the text content of a hast node (sanitized code is plain text). */
function textContent(node: ElementContent): string {
  if (node.type === "text") return node.value;
  if (node.type === "element" && node.children) {
    return node.children.map(textContent).join("");
  }
  return "";
}

/**
 * If `node` is a `<pre><code class="language-*">` block in a language we have
 * loaded, return Shiki's highlighted `<pre>` element to replace it with; otherwise
 * null (leave the original, already-sanitized block untouched — plain code).
 *
 * The returned element has NO inline `style` attributes — all color information
 * has been replaced with CSS class names, recorded in `tokenColorMap` /
 * `bgColorMap`. Callers serve the companion CSS at /shiki.css.
 */
function highlightPre(node: Element): Element | null {
  if (node.tagName !== "pre" || !node.children) return null;
  const code = node.children.find(
    (c): c is Element => c.type === "element" && c.tagName === "code",
  );
  if (!code) return null;
  const lang = languageOf(code);
  if (!lang || !loadedLangs.has(lang)) return null;

  const source = code.children.map(textContent).join("").replace(/\n$/, "");
  // Dual-theme, defaultColor:false → every span carries `--shiki-light` and
  // `--shiki-dark` CSS variable properties (no direct `color:` attribute).
  // We then strip those inline styles and replace with CSS classes (see above).
  const hast = highlighter.codeToHast(source, {
    lang,
    themes: { light: "github-light", dark: "github-dark" },
    defaultColor: false,
  });
  const pre = hast.children.find(
    (c): c is Element => c.type === "element" && c.tagName === "pre",
  );
  if (!pre) return null;
  // Strip all inline styles from the pre subtree and replace with CSS classes.
  stripShikiStyles(pre);
  return pre;
}

/** Recursively replace highlightable `<pre>` blocks in a child list, in place. */
function walk(children: Array<RootContent | ElementContent>): void {
  for (let i = 0; i < children.length; i++) {
    const child = children[i];
    if (child.type !== "element") continue;
    const replaced = highlightPre(child);
    if (replaced) {
      children[i] = replaced;
      continue; // do not descend into Shiki's generated subtree
    }
    if (child.children) walk(child.children);
  }
}

/**
 * Rehype plugin: highlight fenced code blocks with Shiki. Placed AFTER
 * rehype-sanitize in the markdown processor so it only transforms sanitized input.
 */
export function rehypeShikiSync() {
  return (tree: Root): void => {
    walk(tree.children);
  };
}
